# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
inhibit_all_warnings!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ProductionApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |pod_target|
      pod_target.build_configurations.each do |build_config|
        build_config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        build_config.build_settings['LIBTOOLFLAGS'] = '$(inherited) -no_warning_for_no_symbols'
        build_config.build_settings['OTHER_LIBTOOLFLAGS'] = '$(inherited) -no_warning_for_no_symbols'
      end

      pod_target.shell_script_build_phases.each do |phase|
        if phase.name&.include?('[Hermes] Replace Hermes')
          phase.always_out_of_date = '1'
        end
      end
    end
  end
end
